version: "3"
services:
    flask-reservation:
      build: monolith
      environment: 
        - DATABASE_URI=sqlite:///reservation.db
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_APP=app.py
        - PYTHONPATH=./
        - API_GATEWAY_SERVICE=http://nginx-reservation:80
      command: pytest tests/ -cov=reservation --cov-report term-missing
      
    flask-monolith:
      build: monolith
      environment: 
        - DATABASE_URI=sqlite:///monolith.db
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_APP=app.py
        - PYTHONPATH=./
        - RESERVATION_SERVICE=http://nginx-reservation:8080
      command: pytest classes/tests/ -cov=monolith --cov-report term-missing
