openapi: 3.0.1
info:
  title: Booking Service API
  description: Reservation and Seat from GoOutSafe with Microservices
  version: "0.1"
servers:
- url: /
paths:

  /reservation/all: 
    get:
      tags:
      - All reservatinos
      summary: Get all the reservations
      operationId: views.reservation.get_all_reservation
      responses:
        200:
          description: Return all reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'

  /reservation/customers/all: 
    get:
      tags:
      - Reservation list customers
      summary: Get all reservations made by the customer
      operationId: views.customers.get_reservation_list
      responses:
        200:
          description: Return all reservations made by the customer
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'
        401:
          description: User not logged
          content: {}
        403:
          description: User not admitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: You are not a customer

  
  /reservation/owners/all: 
    get:
      tags:
      - Reservation list owners
      summary: Get all reservations made on my own restaurants
      operationId: views.owners.get_reservation_list
      responses:
        200:
          description: Return all reservations made on my own restaurants
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'
        401:
          description: User not logged
          content: {}
        403:
          description: User not admitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: You are not a owner

components:
  schemas:
    Reservation:
      required:
      - booker_id
      - restaurant_id
      - table_id
      - date
      - cancelled
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier
          readOnly: true
          example: 123
        booker_id:
          type: integer
          readOnly: true
          example: 123
        restaurant_id:
          type: integer
          readOnly: true
          example: 123
        table_id:
          type: integer
          readOnly: true
          example: 123
        date:
          type: date
          readOnly: true
          example: "12/10/2020 12:00"
        cancelled:
          type: boolean
          readOnly: false
          example: false
       
  